FROM node:19.4.0

WORKDIR /app

COPY package*.json ./
RUN npm install --save-dev @babel/core@^7.0.0 @babel/preset-env@^7.0.0 babel-jest@^26.0.0 jest@^26.0.0 jest-puppeteer@^5.0.0 puppeteer@^5.4.1 jest-html-reporters


COPY . .

CMD ["npm", "run", "test:report"]
